Make symbol case insensitive
vinumdoc/vinum pull request #7
Opened 2024-11-12 20:23 UTC by MurilloMMartins

In the language description we say that symbols are case-insensitive, so this converts every symbol text to lowercase.
This is done by iterating through a SYMBOL node's text and using the C 'tolower' function.

2024-11-13 10:23 UTC, Grillo-0 commented on src/dry_bison.y
> +		text[i] = tolower(text[i]);
This works for non ASCII chars (e.g. Â)?

2024-11-14 14:57 UTC, MurilloMMartins commented on src/dry_bison.y
> +		text[i] = tolower(text[i]);
Nope, but i worked on a fix.

2024-11-14 20:18 UTC, Grillo-0 requested changes
Make the locale commit be the first one, because the other two doesn't work without it. And merge those two commits, (case-insensitive and Unicode support) as the Unicode is a fix for the case-insensitive one.

2024-11-14 20:18 UTC, Grillo-0 commented on src/dry_bison.y
> +	mbstowcs(wtext, text, len);
Add a `// TODO:` to handle the function return value

2024-11-14 20:18 UTC, Grillo-0 commented on src/dry_bison.y
> +	wcstombs(text, wtext, len);
Same here

2024-11-14 20:18 UTC, Grillo-0 commented on src/dry_bison.y
> +#include <wctype.h>
join this two include blocks

2024-11-14 20:19 UTC, Grillo-0 commented
Also, rebase the branch

2024-12-05 19:07 UTC, Grillo-0 requested changes

2024-12-05 19:07 UTC, Grillo-0 commented on src/dry_bison.y
> +	char *text = ctx.ast.nodes[$1].text;
Due to #10 this doesn't work anymore:

```suggestion
	char *text = VEC_AT(&ctx.ast.nodes, $1).text;
```

2024-12-06 16:16 UTC, artP2 commented
Build passing.

2024-12-07 01:18 UTC, Grillo-0 requested changes
All compiles and seems to work!
Just some nitpicks about the commit messages:

## 1# commit:

s/Added/Add

The commit message must be in the present tense, writing in a way that the commit modification will be added to the project, not as if it were already present in the project.

## 2# commit

The commit message body must be wrapped at 72 columns, to not be difficult to read when doing `git log`.

![image](https://github.com/user-attachments/assets/c3979557-8887-4784-b1c8-b5eedcb73b96)

2024-12-08 14:23 UTC, Grillo-0 approved these changes

2024-12-08 14:23 UTC, merged